-- VDAgent analytical warehouse v3.1.0; PostgreSQL 16+.
-- Source: docs/data-warehouse-data-contract-v3.1.0.md.
-- Apply once to an empty database. No backend tables or cross-database FKs.
BEGIN;
CREATE SCHEMA dw;

CREATE TABLE dw.snapshot_manifest (
    snapshot_id VARCHAR(64) NOT NULL PRIMARY KEY,
    dataset_id VARCHAR(64) NOT NULL,
    dataset_version VARCHAR(16) NOT NULL,
    semantic_version VARCHAR(16) NOT NULL,
    snapshot_date DATE NOT NULL,
    timezone VARCHAR(32) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    price_basis VARCHAR(32) NOT NULL,
    area_basis VARCHAR(32) NOT NULL,
    source_system VARCHAR(64) NOT NULL
);

CREATE TABLE dw.semantic_config (
    config_key VARCHAR(64) NOT NULL PRIMARY KEY,
    config_value VARCHAR(256) NOT NULL,
    value_type VARCHAR(16) NOT NULL,
    semantic_version VARCHAR(16) NOT NULL,
    approval_status VARCHAR(16) NOT NULL,
    description TEXT
);

CREATE TABLE dw.dim_date (
    date_key INTEGER NOT NULL PRIMARY KEY,
    full_date DATE NOT NULL UNIQUE,
    year SMALLINT NOT NULL,
    quarter SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    day_of_month SMALLINT NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    fiscal_quarter VARCHAR(8) NOT NULL
);

CREATE TABLE dw.dim_infrastructure_assets (
    infra_key INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    infra_id VARCHAR(32) NOT NULL UNIQUE,
    infra_name VARCHAR(128) NOT NULL,
    infra_type VARCHAR(32) NOT NULL,
    lifecycle_stage VARCHAR(32) NOT NULL,
    construction_progress_pct DECIMAL(5,2),
    original_completion_year SMALLINT,
    revised_completion_year SMALLINT
);

CREATE TABLE dw.dim_project_profile (
    project_key INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    project_id VARCHAR(32) NOT NULL UNIQUE,
    project_name VARCHAR(128) NOT NULL,
    market_id VARCHAR(32) NOT NULL,
    market_name VARCHAR(64) NOT NULL,
    province_city VARCHAR(64) NOT NULL,
    district VARCHAR(64) NOT NULL,
    developer_name VARCHAR(128) NOT NULL,
    developer_tier VARCHAR(16) NOT NULL,
    developer_origin VARCHAR(16) NOT NULL,
    segment VARCHAR(32) NOT NULL,
    construction_status VARCHAR(32) NOT NULL,
    construction_progress_pct DECIMAL(5,2) NOT NULL,
    is_sales_permit_issued BOOLEAN NOT NULL,
    is_bank_guarantee_issued BOOLEAN NOT NULL,
    max_foreign_quota_exceeded BOOLEAN NOT NULL,
    primary_infra_id VARCHAR(32),
    distance_to_primary_infra_m INTEGER,
    partner_bank_name VARCHAR(64),
    expected_handover_date DATE
);

CREATE TABLE dw.dim_zone_master (
    zone_key INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    zone_id VARCHAR(32) NOT NULL UNIQUE,
    project_key INTEGER NOT NULL REFERENCES dw.dim_project_profile(project_key),
    zone_name VARCHAR(64) NOT NULL,
    zone_type VARCHAR(32) NOT NULL,
    total_floors SMALLINT,
    basement_floors SMALLINT,
    units_per_floor SMALLINT NOT NULL,
    passenger_elevators SMALLINT NOT NULL,
    elevator_ratio DECIMAL(4,1) NOT NULL,
    handover_standard VARCHAR(32) NOT NULL
);

CREATE TABLE dw.dim_unit_master (
    unit_key BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    unit_id VARCHAR(32) NOT NULL UNIQUE,
    unit_code VARCHAR(32) NOT NULL,
    project_key INTEGER NOT NULL REFERENCES dw.dim_project_profile(project_key),
    zone_key INTEGER NOT NULL REFERENCES dw.dim_zone_master(zone_key),
    unit_type VARCHAR(16) NOT NULL,
    bedroom_count SMALLINT NOT NULL,
    bathroom_count SMALLINT NOT NULL,
    net_area_m2 DECIMAL(8,2) NOT NULL,
    gross_area_m2 DECIMAL(8,2) NOT NULL,
    floor_number SMALLINT NOT NULL,
    floor_band VARCHAR(16) NOT NULL,
    balcony_orientation VARCHAR(4) NOT NULL,
    door_orientation VARCHAR(4),
    view_primary_type VARCHAR(32) NOT NULL,
    is_corner_unit BOOLEAN NOT NULL,
    efficiency_ratio DECIMAL(4,3) NOT NULL,
    distance_to_trash_room_m DECIMAL(4,1),
    is_adjacent_elevator BOOLEAN NOT NULL,
    dark_bedroom_count SMALLINT NOT NULL,
    west_facing_exposure_pct DECIMAL(4,2) NOT NULL,
    view_obstruction_distance_m DECIMAL(5,1),
    taboo_view_type VARCHAR(32),
    is_taboo_floor BOOLEAN NOT NULL,
    ext_attributes JSONB
);

CREATE TABLE dw.dim_sales_channel (
    channel_key INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    channel_id VARCHAR(32) NOT NULL UNIQUE,
    channel_name VARCHAR(128) NOT NULL,
    channel_tier VARCHAR(16) NOT NULL,
    active_brokers_count INTEGER
);

CREATE TABLE dw.dim_secondary_market_comps (
    comp_id VARCHAR(32) NOT NULL PRIMARY KEY,
    project_id VARCHAR(32) NOT NULL,
    unit_type VARCHAR(16) NOT NULL,
    floor_band VARCHAR(16) NOT NULL,
    balcony_orientation VARCHAR(4) NOT NULL,
    recorded_resale_date DATE NOT NULL,
    resale_price_per_m2_vnd BIGINT NOT NULL,
    pink_book_status VARCHAR(32) NOT NULL
);

CREATE TABLE dw.fact_market_macro_monthly (
    macro_record_id VARCHAR(32) NOT NULL PRIMARY KEY,
    date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    market_id VARCHAR(32) NOT NULL,
    segment VARCHAR(32) NOT NULL,
    floating_mortgage_rate_pct DECIMAL(4,2) NOT NULL,
    months_of_inventory_moi DECIMAL(4,1),
    absorption_rate_pct DECIMAL(5,2) NOT NULL,
    median_household_income_vnd BIGINT NOT NULL,
    macro_price_to_income_ratio DECIMAL(4,1)
);

CREATE TABLE dw.fact_unit_price_history (
    price_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    unit_key BIGINT NOT NULL REFERENCES dw.dim_unit_master(unit_key),
    effective_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    old_asking_price_vnd BIGINT NOT NULL,
    new_asking_price_vnd BIGINT NOT NULL,
    price_change_pct DECIMAL(5,2) NOT NULL,
    change_reason VARCHAR(64)
);

CREATE TABLE dw.fact_sales_funnel_daily (
    funnel_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    unit_key BIGINT NOT NULL REFERENCES dw.dim_unit_master(unit_key),
    web_listing_views INTEGER NOT NULL,
    inquiry_leads_count SMALLINT NOT NULL,
    site_visits_count SMALLINT NOT NULL,
    booking_reservations SMALLINT NOT NULL,
    booking_cancellations SMALLINT NOT NULL,
    cancellation_reason VARCHAR(64)
);

CREATE TABLE dw.fact_unit_inventory_snapshot (
    snapshot_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    unit_key BIGINT NOT NULL REFERENCES dw.dim_unit_master(unit_key),
    project_key INTEGER NOT NULL REFERENCES dw.dim_project_profile(project_key),
    zone_key INTEGER NOT NULL REFERENCES dw.dim_zone_master(zone_key),
    channel_key INTEGER NOT NULL REFERENCES dw.dim_sales_channel(channel_key),
    launch_batch_id VARCHAR(32) NOT NULL,
    release_date DATE NOT NULL,
    inventory_status VARCHAR(16) NOT NULL,
    sold_date DATE,
    unsold_days_dom INTEGER NOT NULL,
    is_overdue_flag BOOLEAN NOT NULL,
    asking_price_vnd BIGINT NOT NULL,
    discount_pct DECIMAL(5,2) NOT NULL,
    concession_value_vnd BIGINT NOT NULL,
    net_price_vnd BIGINT NOT NULL,
    asking_price_per_m2 BIGINT NOT NULL,
    net_price_per_m2 BIGINT NOT NULL,
    subsidy_duration_mo SMALLINT NOT NULL,
    principal_grace_mo SMALLINT NOT NULL,
    base_commission_pct DECIMAL(4,2) NOT NULL,
    spiff_bonus_vnd BIGINT,
    is_exclusive_lock BOOLEAN NOT NULL,
    PRIMARY KEY (snapshot_date_key, unit_key)
);

CREATE TABLE dw.fact_sales_channel_performance (
    snapshot_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    channel_key INTEGER NOT NULL REFERENCES dw.dim_sales_channel(channel_key),
    project_key INTEGER NOT NULL REFERENCES dw.dim_project_profile(project_key),
    assigned_units_count INTEGER NOT NULL,
    sold_units_count INTEGER NOT NULL,
    absorption_rate_pct DECIMAL(5,2) NOT NULL,
    avg_days_to_sell INTEGER,
    locked_inventory_over_90d INTEGER NOT NULL,
    PRIMARY KEY (snapshot_date_key, channel_key, project_key)
);

CREATE TABLE dw.dm_unit_friction_diagnostics (
    diagnostic_id VARCHAR(64) NOT NULL PRIMARY KEY,
    snapshot_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    unit_key BIGINT NOT NULL REFERENCES dw.dim_unit_master(unit_key),
    unit_code VARCHAR(32) NOT NULL,
    project_name VARCHAR(128) NOT NULL,
    zone_name VARCHAR(64) NOT NULL,
    unsold_days_dom INTEGER NOT NULL,
    price_spread_vs_peer_pct DECIMAL(5,2),
    ticket_size_vs_income_ratio DECIMAL(4,1),
    physical_defect_penalty SMALLINT NOT NULL,
    thermal_view_penalty SMALLINT NOT NULL,
    secondary_price_gap_pct DECIMAL(5,2),
    funnel_dropoff_rate_pct DECIMAL(5,2),
    primary_cause_code VARCHAR(32) NOT NULL,
    recommended_action VARCHAR(64) NOT NULL
);

CREATE TABLE dw.unit_diagnostic_causes (
    diagnostic_id VARCHAR(64) NOT NULL REFERENCES dw.dm_unit_friction_diagnostics(diagnostic_id),
    cause_code VARCHAR(32) NOT NULL,
    unit_key BIGINT NOT NULL REFERENCES dw.dim_unit_master(unit_key),
    snapshot_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    severity_rank SMALLINT NOT NULL,
    attribution_score DECIMAL(4,3) NOT NULL,
    evidence_artifact_id VARCHAR(64),
    PRIMARY KEY (diagnostic_id, cause_code)
);

ALTER TABLE dw.snapshot_manifest ADD CONSTRAINT ck_snapshot_manifest_01 CHECK (timezone = 'Asia/Ho_Chi_Minh');
ALTER TABLE dw.snapshot_manifest ADD CONSTRAINT ck_snapshot_manifest_02 CHECK (currency = 'VND');
ALTER TABLE dw.snapshot_manifest ADD CONSTRAINT ck_snapshot_manifest_03 CHECK (price_basis = 'ASKING_EXCL_VAT_EXCL_MAINT');
ALTER TABLE dw.snapshot_manifest ADD CONSTRAINT ck_snapshot_manifest_04 CHECK (area_basis = 'NET_INTERNAL_M2');
ALTER TABLE dw.snapshot_manifest ADD CONSTRAINT ck_snapshot_manifest_05 CHECK (dataset_id = 'vdagent_dw_re');
ALTER TABLE dw.snapshot_manifest ADD CONSTRAINT ck_snapshot_manifest_06 CHECK (source_system = 'ENTERPRISE_DW_RE');

ALTER TABLE dw.semantic_config ADD CONSTRAINT ck_semantic_config_01 CHECK (value_type IN ('INTEGER','DECIMAL','BOOLEAN','STRING'));
ALTER TABLE dw.semantic_config ADD CONSTRAINT ck_semantic_config_02 CHECK (approval_status IN ('APPROVED','PENDING'));

ALTER TABLE dw.dim_date ADD CONSTRAINT ck_dim_date_01 CHECK (date_key = TO_CHAR(full_date, 'YYYYMMDD')::integer);
ALTER TABLE dw.dim_date ADD CONSTRAINT ck_dim_date_02 CHECK (year = EXTRACT(YEAR FROM full_date));
ALTER TABLE dw.dim_date ADD CONSTRAINT ck_dim_date_03 CHECK (quarter = EXTRACT(QUARTER FROM full_date));
ALTER TABLE dw.dim_date ADD CONSTRAINT ck_dim_date_04 CHECK (month = EXTRACT(MONTH FROM full_date));
ALTER TABLE dw.dim_date ADD CONSTRAINT ck_dim_date_05 CHECK (day_of_month = EXTRACT(DAY FROM full_date));
ALTER TABLE dw.dim_date ADD CONSTRAINT ck_dim_date_06 CHECK (is_weekend = (EXTRACT(ISODOW FROM full_date) IN (6, 7)));
ALTER TABLE dw.dim_date ADD CONSTRAINT ck_dim_date_07 CHECK (fiscal_quarter = year::text || '-Q' || quarter::text);

ALTER TABLE dw.dim_infrastructure_assets ADD CONSTRAINT ck_dim_infrastructure_assets_01 CHECK (infra_type IN ('URBAN_METRO','RING_ROAD','EXPRESSWAY','BRIDGE','AIRPORT'));
ALTER TABLE dw.dim_infrastructure_assets ADD CONSTRAINT ck_dim_infrastructure_assets_02 CHECK (lifecycle_stage IN ('PLANNING_APPROVED','UNDER_CONSTRUCTION','COMMERCIAL_OPERATION'));
ALTER TABLE dw.dim_infrastructure_assets ADD CONSTRAINT ck_dim_infrastructure_assets_03 CHECK (construction_progress_pct IS NULL OR construction_progress_pct BETWEEN 0 AND 100);
ALTER TABLE dw.dim_infrastructure_assets ADD CONSTRAINT ck_dim_infrastructure_assets_04 CHECK (original_completion_year IS NULL OR original_completion_year > 0);
ALTER TABLE dw.dim_infrastructure_assets ADD CONSTRAINT ck_dim_infrastructure_assets_05 CHECK (revised_completion_year IS NULL OR revised_completion_year > 0);

ALTER TABLE dw.dim_project_profile ADD CONSTRAINT ck_dim_project_profile_01 CHECK (developer_tier IN ('TIER_1','TIER_2','TIER_3'));
ALTER TABLE dw.dim_project_profile ADD CONSTRAINT ck_dim_project_profile_02 CHECK (developer_origin IN ('DOMESTIC','FOREIGN_FDI'));
ALTER TABLE dw.dim_project_profile ADD CONSTRAINT ck_dim_project_profile_03 CHECK (segment IN ('AFFORDABLE','MID','MID_HIGH','LUXURY'));
ALTER TABLE dw.dim_project_profile ADD CONSTRAINT ck_dim_project_profile_04 CHECK (construction_status IN ('FOUNDATION','SUPERSTRUCTURE','TOPPED_OUT','HANDED_OVER'));
ALTER TABLE dw.dim_project_profile ADD CONSTRAINT ck_dim_project_profile_05 CHECK (construction_progress_pct BETWEEN 0 AND 100);
ALTER TABLE dw.dim_project_profile ADD CONSTRAINT ck_dim_project_profile_06 CHECK (distance_to_primary_infra_m IS NULL OR distance_to_primary_infra_m >= 0);

ALTER TABLE dw.dim_zone_master ADD CONSTRAINT ck_dim_zone_master_01 CHECK (zone_type IN ('HIGH_RISE_TOWER','LOW_RISE_VILLA','SHOPHOUSE'));
ALTER TABLE dw.dim_zone_master ADD CONSTRAINT ck_dim_zone_master_02 CHECK (handover_standard IN ('BARE_SHELL','BASIC_FINISH','FULLY_FURNISHED'));
ALTER TABLE dw.dim_zone_master ADD CONSTRAINT ck_dim_zone_master_03 CHECK (total_floors IS NULL OR total_floors > 0);
ALTER TABLE dw.dim_zone_master ADD CONSTRAINT ck_dim_zone_master_04 CHECK (basement_floors IS NULL OR basement_floors >= 0);
ALTER TABLE dw.dim_zone_master ADD CONSTRAINT ck_dim_zone_master_05 CHECK (units_per_floor > 0);
ALTER TABLE dw.dim_zone_master ADD CONSTRAINT ck_dim_zone_master_06 CHECK (passenger_elevators > 0);
ALTER TABLE dw.dim_zone_master ADD CONSTRAINT ck_dim_zone_master_07 CHECK (elevator_ratio = ROUND(units_per_floor::numeric / passenger_elevators, 1));

ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_01 CHECK (unit_type IN ('STUDIO','1PN','2PN','3PN','4PN','PENTHOUSE'));
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_02 CHECK (bedroom_count >= 0);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_03 CHECK (bathroom_count >= 0);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_04 CHECK (dark_bedroom_count BETWEEN 0 AND bedroom_count);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_05 CHECK (net_area_m2 > 0 AND gross_area_m2 >= net_area_m2);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_06 CHECK (floor_number > 0);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_07 CHECK (floor_band IN ('LOW','MID','HIGH','TOP'));
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_08 CHECK (balcony_orientation IN ('N','NE','E','SE','S','SW','W','NW'));
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_09 CHECK (door_orientation IS NULL OR door_orientation IN ('N','NE','E','SE','S','SW','W','NW'));
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_10 CHECK (view_primary_type IN ('RIVER','PARK','POOL','CITY_OPEN','OBSTRUCTED'));
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_11 CHECK (efficiency_ratio = ROUND(net_area_m2 / gross_area_m2, 3));
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_12 CHECK (efficiency_ratio > 0 AND efficiency_ratio <= 1);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_13 CHECK (distance_to_trash_room_m IS NULL OR distance_to_trash_room_m >= 0);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_14 CHECK (west_facing_exposure_pct BETWEEN 0 AND 1);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_15 CHECK (view_obstruction_distance_m IS NULL OR view_obstruction_distance_m >= 0);
ALTER TABLE dw.dim_unit_master ADD CONSTRAINT ck_dim_unit_master_16 CHECK (taboo_view_type IS NULL OR taboo_view_type IN ('CEMETERY','WASTE_STATION','TEMPLE','NONE'));

ALTER TABLE dw.dim_sales_channel ADD CONSTRAINT ck_dim_sales_channel_01 CHECK (channel_tier IN ('TIER_1_EXCLUSIVE','TIER_2_GENERAL','INHOUSE'));
ALTER TABLE dw.dim_sales_channel ADD CONSTRAINT ck_dim_sales_channel_02 CHECK (active_brokers_count IS NULL OR active_brokers_count >= 0);

ALTER TABLE dw.dim_secondary_market_comps ADD CONSTRAINT ck_dim_secondary_market_comps_01 CHECK (unit_type IN ('1PN','2PN','3PN'));
ALTER TABLE dw.dim_secondary_market_comps ADD CONSTRAINT ck_dim_secondary_market_comps_02 CHECK (floor_band IN ('LOW','MID','HIGH','TOP'));
ALTER TABLE dw.dim_secondary_market_comps ADD CONSTRAINT ck_dim_secondary_market_comps_03 CHECK (balcony_orientation IN ('N','NE','E','SE','S','SW','W','NW'));
ALTER TABLE dw.dim_secondary_market_comps ADD CONSTRAINT ck_dim_secondary_market_comps_04 CHECK (resale_price_per_m2_vnd > 0);
ALTER TABLE dw.dim_secondary_market_comps ADD CONSTRAINT ck_dim_secondary_market_comps_05 CHECK (pink_book_status IN ('PINK_BOOK_AVAILABLE','SPA_ASSIGNMENT'));

ALTER TABLE dw.fact_market_macro_monthly ADD CONSTRAINT ck_fact_market_macro_monthly_01 CHECK (segment IN ('AFFORDABLE','MID','MID_HIGH','LUXURY'));
ALTER TABLE dw.fact_market_macro_monthly ADD CONSTRAINT ck_fact_market_macro_monthly_02 CHECK (floating_mortgage_rate_pct >= 0);
ALTER TABLE dw.fact_market_macro_monthly ADD CONSTRAINT ck_fact_market_macro_monthly_03 CHECK (months_of_inventory_moi IS NULL OR months_of_inventory_moi >= 0);
ALTER TABLE dw.fact_market_macro_monthly ADD CONSTRAINT ck_fact_market_macro_monthly_04 CHECK (absorption_rate_pct BETWEEN 0 AND 100);
ALTER TABLE dw.fact_market_macro_monthly ADD CONSTRAINT ck_fact_market_macro_monthly_05 CHECK (median_household_income_vnd > 0);
ALTER TABLE dw.fact_market_macro_monthly ADD CONSTRAINT ck_fact_market_macro_monthly_06 CHECK (macro_price_to_income_ratio IS NULL OR macro_price_to_income_ratio >= 0);

ALTER TABLE dw.fact_unit_price_history ADD CONSTRAINT ck_fact_unit_price_history_01 CHECK (old_asking_price_vnd > 0 AND new_asking_price_vnd > 0);
ALTER TABLE dw.fact_unit_price_history ADD CONSTRAINT ck_fact_unit_price_history_02 CHECK (price_change_pct = ROUND((new_asking_price_vnd - old_asking_price_vnd)::numeric * 100 / old_asking_price_vnd, 2));
ALTER TABLE dw.fact_unit_price_history ADD CONSTRAINT ck_fact_unit_price_history_03 CHECK (change_reason IS NULL OR change_reason IN ('STIMULATE_SLOW_MOVING','MARKET_RALLY','CAMPAIGN'));

ALTER TABLE dw.fact_sales_funnel_daily ADD CONSTRAINT ck_fact_sales_funnel_daily_01 CHECK (web_listing_views >= 0 AND inquiry_leads_count >= 0 AND site_visits_count >= 0);
ALTER TABLE dw.fact_sales_funnel_daily ADD CONSTRAINT ck_fact_sales_funnel_daily_02 CHECK (booking_reservations >= 0 AND booking_cancellations >= 0);
ALTER TABLE dw.fact_sales_funnel_daily ADD CONSTRAINT ck_fact_sales_funnel_daily_03 CHECK (cancellation_reason IS NULL OR cancellation_reason IN ('PRICE_TOO_HIGH','DEFECT_FOUND','LOAN_REJECTED'));

ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_01 CHECK (inventory_status IN ('AVAILABLE','BOOKED','SOLD'));
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_02 CHECK ((inventory_status = 'SOLD' AND sold_date IS NOT NULL AND sold_date >= release_date) OR (inventory_status <> 'SOLD' AND sold_date IS NULL));
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_03 CHECK (release_date <= TO_DATE(snapshot_date_key::text, 'YYYYMMDD'));
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_04 CHECK (sold_date IS NULL OR sold_date <= TO_DATE(snapshot_date_key::text, 'YYYYMMDD'));
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_05 CHECK (unsold_days_dom >= 0);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_06 CHECK (asking_price_vnd > 0 AND concession_value_vnd >= 0 AND net_price_vnd > 0);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_07 CHECK (discount_pct BETWEEN 0 AND 100);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_08 CHECK (net_price_vnd = ROUND(asking_price_vnd::numeric * (1 - discount_pct / 100) - concession_value_vnd));
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_09 CHECK (net_price_vnd <= asking_price_vnd);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_10 CHECK (asking_price_per_m2 > 0 AND net_price_per_m2 > 0);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_11 CHECK (subsidy_duration_mo >= 0 AND principal_grace_mo >= 0);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_12 CHECK (base_commission_pct BETWEEN 0 AND 100);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_13 CHECK (spiff_bonus_vnd IS NULL OR spiff_bonus_vnd >= 0);
ALTER TABLE dw.fact_unit_inventory_snapshot ADD CONSTRAINT ck_fact_unit_inventory_snapshot_14 CHECK (unsold_days_dom = COALESCE(sold_date, TO_DATE(snapshot_date_key::text, 'YYYYMMDD')) - release_date);

ALTER TABLE dw.fact_sales_channel_performance ADD CONSTRAINT ck_fact_sales_channel_performance_01 CHECK (assigned_units_count >= 0 AND sold_units_count BETWEEN 0 AND assigned_units_count);
ALTER TABLE dw.fact_sales_channel_performance ADD CONSTRAINT ck_fact_sales_channel_performance_02 CHECK (absorption_rate_pct BETWEEN 0 AND 100);
ALTER TABLE dw.fact_sales_channel_performance ADD CONSTRAINT ck_fact_sales_channel_performance_03 CHECK (avg_days_to_sell IS NULL OR avg_days_to_sell >= 0);
ALTER TABLE dw.fact_sales_channel_performance ADD CONSTRAINT ck_fact_sales_channel_performance_04 CHECK (locked_inventory_over_90d BETWEEN 0 AND assigned_units_count);
ALTER TABLE dw.fact_sales_channel_performance ADD CONSTRAINT ck_fact_sales_channel_performance_05 CHECK (CASE WHEN assigned_units_count = 0 THEN absorption_rate_pct = 0 ELSE absorption_rate_pct = ROUND(sold_units_count::numeric * 100 / assigned_units_count, 2) END);

ALTER TABLE dw.dm_unit_friction_diagnostics ADD CONSTRAINT ck_dm_unit_friction_diagnostics_01 CHECK (unsold_days_dom > 0);
ALTER TABLE dw.dm_unit_friction_diagnostics ADD CONSTRAINT ck_dm_unit_friction_diagnostics_02 CHECK (physical_defect_penalty BETWEEN 0 AND 100 AND thermal_view_penalty BETWEEN 0 AND 100);
ALTER TABLE dw.dm_unit_friction_diagnostics ADD CONSTRAINT ck_dm_unit_friction_diagnostics_03 CHECK (funnel_dropoff_rate_pct IS NULL OR funnel_dropoff_rate_pct BETWEEN 0 AND 100);
ALTER TABLE dw.dm_unit_friction_diagnostics ADD CONSTRAINT ck_dm_unit_friction_diagnostics_04 CHECK (ticket_size_vs_income_ratio IS NULL OR ticket_size_vs_income_ratio >= 0);
ALTER TABLE dw.dm_unit_friction_diagnostics ADD CONSTRAINT ck_dm_unit_friction_diagnostics_05 CHECK (primary_cause_code IN ('LEGAL_PERMIT_BARRIER','SEVERE_PHYSICAL_DEFECT','EXTREME_THERMAL_EXPOSURE','SECONDARY_ARBITRAGE','LUMP_SUM_TICKET_BARRIER','OVERPRICED_VS_PEER','LOW_SALES_INCENTIVE','DEEP_FUNNEL_DROP_OFF'));

ALTER TABLE dw.unit_diagnostic_causes ADD CONSTRAINT ck_unit_diagnostic_causes_01 CHECK (severity_rank > 0);
ALTER TABLE dw.unit_diagnostic_causes ADD CONSTRAINT ck_unit_diagnostic_causes_02 CHECK (attribution_score > 0 AND attribution_score <= 1);

-- Business grain uniqueness inferred from the contract (surrogate PK remains intact).
ALTER TABLE dw.fact_sales_funnel_daily ADD CONSTRAINT uq_funnel_unit_day UNIQUE (date_key, unit_key);
ALTER TABLE dw.fact_market_macro_monthly ADD CONSTRAINT uq_macro_market_segment_month UNIQUE (date_key, market_id, segment);
ALTER TABLE dw.dm_unit_friction_diagnostics ADD CONSTRAINT uq_diagnostic_unit_snapshot UNIQUE (snapshot_date_key, unit_key);

-- Indexes complement PK/UK/FK indexes for common analytical access paths.
CREATE INDEX ix_project_market_segment ON dw.dim_project_profile (market_id, segment);
CREATE INDEX ix_zone_project ON dw.dim_zone_master (project_key);
CREATE INDEX ix_unit_project_zone ON dw.dim_unit_master (project_key, zone_key);
CREATE INDEX ix_unit_peer_group ON dw.dim_unit_master (project_key, unit_type, floor_band, balcony_orientation, net_area_m2);
CREATE INDEX ix_comp_peer_recent ON dw.dim_secondary_market_comps (project_id, unit_type, floor_band, balcony_orientation, recorded_resale_date DESC);
CREATE INDEX ix_macro_market_recent ON dw.fact_market_macro_monthly (market_id, segment, date_key DESC);
CREATE INDEX ix_price_unit_recent ON dw.fact_unit_price_history (unit_key, effective_date_key DESC);
CREATE INDEX ix_funnel_unit_recent ON dw.fact_sales_funnel_daily (unit_key, date_key DESC);
CREATE INDEX ix_inventory_unit_recent ON dw.fact_unit_inventory_snapshot (unit_key, snapshot_date_key DESC);
CREATE INDEX ix_inventory_project_snapshot_status ON dw.fact_unit_inventory_snapshot (project_key, snapshot_date_key, inventory_status);
CREATE INDEX ix_inventory_zone_snapshot ON dw.fact_unit_inventory_snapshot (zone_key, snapshot_date_key);
CREATE INDEX ix_inventory_channel_snapshot ON dw.fact_unit_inventory_snapshot (channel_key, snapshot_date_key);
CREATE INDEX ix_channel_project_snapshot ON dw.fact_sales_channel_performance (project_key, snapshot_date_key DESC);
CREATE INDEX ix_diagnostic_cause_snapshot ON dw.dm_unit_friction_diagnostics (primary_cause_code, snapshot_date_key DESC);
CREATE INDEX ix_cause_unit_snapshot ON dw.unit_diagnostic_causes (unit_key, snapshot_date_key DESC);
CREATE INDEX ix_cause_code_snapshot ON dw.unit_diagnostic_causes (cause_code, snapshot_date_key DESC);
COMMIT;
